###
GET http://localhost:1212/tampil

###
GET http://localhost:1212/tampilkan/1 


###
DELETE  http://localhost:3000/delete/18

###
POST http://localhost:1122/addMhs
Content-Type: application/json

{
    "nim":"126811",
    "nama":"marno",
    "jurusan":"THP"
}

### 
PUT http://localhost:3000/ubah/2
Content-Type: :application/json

{
    "nim":"'123123'",
    "nama":"'fadel'",
    "jurusan":"'IPA'"

}

