###
GET http://localhost:3000/tampil


###
GET http://localhost:3000/tampilMk

###
GET http://localhost:3000/tampil/2

###
DELETE  http://localhost:3000/delete/10

###
POST http://localhost:3000/addMhs
Content-Type: application/json

{
    "nim":"126811",
    "nama":"marno",
    "jurusan":"THP"
}

### 
POST  http://localhost:3000/ubah/19
Content-Type: :application/json

{
    "nim":"'19'",
    "nama":"'fadel'",
    "jurusan":"'IPA'"

}


###
POST http://localhost:3000/auth/api/v1/register
Content-Type: application/json
# Content-Type: application/x-www-form-urlencoded

{
    "username":"1",
    "email":"1@gmail.com",
    "password":"1",
    "role":"2"
}


###
POST http://localhost:3000/auth/api/v1/login
Content-Type: application/json

{
    "email":"1@gmail.com",
    "password":"1"
}


###

GET http://localhost:3000/auth/api/v1/rahasia HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb3dzIjpbeyJpZF91c2VyIjo5LCJ1c2VybmFtZSI6IjEiLCJlbWFpbCI6IjFAZ21haWwuY29tIiwicGFzc3dvcmQiOiJjNGNhNDIzOGEwYjkyMzgyMGRjYzUwOWE2Zjc1ODQ5YiIsInJvbGUiOjEsInRnbF9jcmVhdGVkIjoiMjAyMy0xMS0wM1QwNzoyMjoxOS4wMDBaIn1dLCJpYXQiOjE2OTg5OTg3NjgsImV4cCI6MTY5OTAwMDIwOH0.rcUGy1ccJlBGbzcwrg1ezKA31kGH0miQnCrZSLeo3K4
Content-Type: application/json

{
    "role":"1"
}











